version: 2.1

orbs:
  slack: circleci/slack@4.12.5
  gcp-cli: circleci/gcp-cli@3.1.1
  python: circleci/python@2.1.1

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:current

commands:
  gcloud-sdk:
    description: 'Install and configure gcloud sdk'
    steps:
      - run: |
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet auth configure-docker
          gcloud --quiet components install gke-gcloud-auth-plugin
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> ~/.profile
          gcloud container clusters get-credentials ${EMBEDDINGS_K8S_CLUSTER} --region ${EMBEDDINGS_GCP_REGION} --project ${EMBEDDINGS_GCP_PROJECT}

jobs:
  build-and-test:
    executor: ubuntu-executor
    steps:
      - checkout

      - run:
          name: Configure git
          command: |
            mkdir -p ~/.ssh/
            ssh-keyscan github.com > ~/.ssh/known_hosts
            git config --global user.email "circleci@zia.ai"
            git config --global user.name "CircleCI"

      - run:
          name: clone e2e and copy just aio.sh file
          command: |            
            git clone git@github.com:zia-ai/e2e-testing.git /tmp/e2e-testing
            cp /tmp/e2e-testing/aio.sh .

      - run: 
          name: dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            sudo apt install -y docker
            sudo apt-get install -y systemd-timesyncd
            sudo systemctl enable systemd-timesyncd
            sudo systemctl start systemd-timesyncd
            sudo apt-get install -y ntpdate
            sudo apt-get install -y net-tools
            mkdir -p aio-logs
      - gcp-cli/setup:
          use_oidc: true
          components: docker-credential-gcr kubectl --quiet
      - gcloud-sdk

      - python/install-packages:
          pkg-manager: pip
      - run:
          # aio script is in a private repo
          # aio script defaults to dev branch override with backend AIO_TAG_OVERRIDE=<release value> i.e AIO_TAG_OVERRIDE=v1.67.2 
          name: Start AIO container
          command: EMBEDDINGS_K8S_FORWARD=1 ./aio.sh start
      - run:
          # Should output like http://172.17.0.2:8888 in CI or http://172.17.0.3:8888 if you are within an existing docker locally
          # Going via a file aio.ip because each step of CircleCI is a new shell so env variables don't pass between
          name: Set Local IP of AIO container to aio.ip text file
          command: echo http:\/\/`docker inspect --format '{{ .NetworkSettings.IPAddress }}' aio`":8888" > aio.ip
      - run:
          name: Run tests (env variables in project settings)
          command: HF_ENVIRONMENT=test HF_LOG_LEVEL=WARNING HF_LOG_CONSOLE_ENABLE=TRUE BASE_URL_TEST=`cat ./aio.ip` pytest -s --log-cli-level=WARNING --cov ./humanfirst/ --cov-report html --cov-report term

workflows:
  test-aio: 
    jobs:
      - build-and-test:
          context:
            - org-global
