version: 2.1

orbs:
  slack: circleci/slack@4.12.5
  gcp-cli: circleci/gcp-cli@3.1.1
  python: circleci/python@2.1.1

executors:
  ubuntu-executor:
    machine:
      image: ubuntu-2204:current

commands:
  gcloud-sdk:
    description: 'Install and configure gcloud sdk'
    steps:
      - run: |
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet auth configure-docker
          gcloud --quiet components install gke-gcloud-auth-plugin
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> ~/.profile
          gcloud --quiet container clusters get-credentials zia-prod-1 --zone us-east1-b --project trial-184203
          kubectl config rename-context gke_trial-184203_us-east1-b_zia-prod-1 staging

jobs:
  build-and-test:
    executor: ubuntu-executor
    steps:
      - checkout

      - run:
          name: Configure git
          command: |
            mkdir -p ~/.ssh/
            ssh-keyscan github.com > ~/.ssh/known_hosts
            git config --global user.email "circleci@zia.ai"
            git config --global user.name "CircleCI"

      - run:
          name: clone e2e and copy just aio.sh file
          command: |            
            git clone https://${GH_USERNAME}:${GH_PERSONAL_TOKEN}@github.com/zia-ai/e2e-testing.git /tmp/e2e-testing
            cp /tmp/e2e-testing/aio.sh .

      - run: 
          name: dependencies
          command: |
            sudo apt update
            sudo apt install -y docker
            sudo apt-get install systemd-timesyncd -y
            sudo systemctl enable systemd-timesyncd
            sudo systemctl start systemd-timesyncd
            sudo apt-get install ntpdate -y
            sudo apt-get install net-tools -y
            mkdir -p aio-logs
      - gcp-cli/setup:
          use_oidc: true
          components: docker-credential-gcr kubectl --quiet
      - gcloud-sdk

      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Start AIO container
          command: EMBEDDINGS_K8S_FORWARD=1 ./aio.sh start
      - run:
          # Should output like http://172.17.0.2:8888 in CI or http://172.17.0.3:8888 if you are within an existing docker locally
          # Using Circle CI have to push it to BASH_ENV as each step is a new shell
          name: Set Local IP of AIO container
          command: export BASE_URL_TEST=http:\/\/`docker inspect --format '{{ .NetworkSettings.IPAddress }}' aio`":8888" && echo 'export BASE_URL_TEST=${BASE_URL_TEST} >> $BASH_ENV'
      - run:
          name: Run tests (env variables in project settings)
          command: HF_ENVIRONMENT=test HF_LOG_LEVEL=WARNING HF_LOG_CONSOLE_ENABLE=TRUE pytest -s --log-cli-level=WARNING --cov ./humanfirst/ --cov-report html --cov-report term

workflows:
  test-aio: 
    jobs:
      - build-and-test:
          context:
            - org-global
