version: 2.1

orbs:
  slack: circleci/slack@4.12.5
  gcp-cli: circleci/gcp-cli@3.1.1
  python: circleci/python@2.1.1

executors:
  ubuntu-executor:
    machine:
      image: default

commands:
  gcloud-sdk:
    description: 'Install and configure gcloud sdk'
    steps:
      - run: |
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          gcloud --quiet auth configure-docker
          gcloud --quiet components install gke-gcloud-auth-plugin
          echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> ~/.profile
          gcloud --quiet container clusters get-credentials zia-prod-1 --zone us-east1-b --project trial-184203
          kubectl config rename-context gke_trial-184203_us-east1-b_zia-prod-1 staging


jobs:
  build-and-test:
    executor: ubuntu-executor
    steps:
      - checkout
      - run: 
          name: dependencies
          command: |
            sudo apt update
            sudo apt install -y docker
            sudo apt-get install systemd-timesyncd -y
            sudo systemctl enable systemd-timesyncd
            sudo systemctl start systemd-timesyncd
            sudo apt-get install ntpdate -y
            sudo apt-get install net-tools -y
            mkdir -p aio-logs
      - gcp-cli/setup:
          use_oidc: true
          components: docker-credential-gcr kubectl --quiet
      - gcloud-sdk

      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Start AIO container
          command: EMBEDDINGS_K8S_FORWARD=1 ./aio.sh start
      - run:
          name: Set Local IP of AIO container
          command: BASE_URL_TEST=http:\\`docker inspect --format '{{ .NetworkSettings.IPAddress }}' aio`":8888" && echo $BASE_URL_TEST
      - run:
          name: Run tests 
          command: HF_ENVIRONMENT=test BASE_URL_TEST=$BASE_URL_TEST pytest --cov ./humanfirst/ --cov-report html --cov-report term

workflows:
  test-aio: 
    jobs:
      - build-and-test:
          context:
            - org-global
